#!/usr/bin/env ruby
require 'compare_with_wikidata'

if ARGV.size != 2
  abort "Usage: #{$PROGRAM_NAME} MEDIAWIKI_SITE PAGE_TITLE
e.g. compare_with_wikidata www.wikidata.org 'User:Mhl20/Fibonacci test'
"
end

mediawiki_site, page_title = ARGV

page = CompareWithWikidata::MediawikiPage.new(mediawiki_site: mediawiki_site, page_title: page_title)

wikitext = CompareWithWikidata::MediawikiText.new(mediawiki_page: page)

if ENV.key?('DEBUG')
  puts wikitext
else
  page.replace_output(wikitext)
  puts "Done: Updated #{page_title} on #{mediawiki_site}"
end
